/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:f45f3b44-d35f-47c0-b1ef-ea1377f6fc24",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_uqX6SjOkw",
    "aws_user_pools_web_client_id": "rc2jk0nrr5up0dav48rfujt8g",
    "oauth": {},
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "LiveTV",
            "endpoint": "https://fsu01kt5xe.execute-api.eu-west-1.amazonaws.com/dev",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "livetvbucket211049-dev",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
